
## CONFIG/CONSTANTS FILE ##

## some stuff can obviously be changed, like move_increments, and fps
## whilst some stuff, like colors, origin, the heights of objects are not to be touched
## but are instead provided as constants that are used by other classes


## PYGAME DISPLAY STUFF ##

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 700
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

## SCORE INFO ##

SCORE_FONT_SIZE = 15

SCORE_LOCATIONX = 450
SCORE_LOCATIONY = 10

HIGHSCORE_LOCATIONX = 20
HIGHSCORE_LOCATIONY = 10

CAPTION = "INVADERS"

## FRAME RATE ##

FPS = 60.0


## COLORS ##

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)


## COORDINATES (GENERAL) ##

ORIGIN = (0, 0)

## SPACESHIP STUFF ##

INIT_SPACESHIP_X = (SCREEN_WIDTH // 2)
INIT_SPACESHIP_Y = SCREEN_HEIGHT - 60

MOVE_INCREMENT = 8

SPACESHIP_HEIGHT = 45
SPACESHIP_WIDTH = 70


## SPACESHIP PROJECTILE STUFF ##

SP_PROJECTILE_ACCELERATION = 3
SP_PROJECTILE_MOVE_INCREMENT = 2
SP_PROJECTILE_MAX_SPEED = 30

## ENEMY STUFF ##

INIT_ENEMY_X = SCREEN_WIDTH // 6
INIT_ENEMY_Y = 80

ENEMY_WIDTH = 80
ENEMY_HEIGHT = 60

ENEMY_HOR_DIST = int(ENEMY_WIDTH / 6)
ENEMY_VERT_DIST = ENEMY_HEIGHT / 5

NUM_ENEMIES = 4

INIT_MOV_X = 2
INIT_MOV_Y = 20

MOV_X_200 = 3
MOV_X_400 = 4
MOV_X_600 = 5

MOV_Y_200 = 20
MOV_Y_400 = 35
MOV_Y_600 = 35


## ENEMY PROJECTILE - FIREBALL STUFF ##

FIREBALL_XMOVE_INCREMENT = 2
FIREBALL_YMOVE_INCREMENT = 5

GRAVITY = 1
FIREBALL_MAX_YSPEED = 8

## ENEMY KILL SCORE ##
KILL_SCORE = 20

